producto/urls.py
from django.urls import path
from . import views

producto_patterns = ([
                         path('producto/gestionar', views.ProductManage.as_view(), name='manage'),
                         path('producto/create/', views.ProductCreate.as_view(), name='create'),
                         path('producto/update/<int:pk>/', views.ProductUpdate.as_view(), name='update'),
                         path('producto/delete/<int:pk>/', views.ProductoDelete.as_view(), name='delete'),
                         path('categoria/gestionar', views.CategoriaList.as_view(), name='categoria_index'),
                         path('categoria/create/', views.CategoriaCreate.as_view(), name='categoria_create'),
                         path('categoria/update/<int:pk>/', views.CategoriaUpdate.as_view(), name='categoria_update'),
                         path('categoria/delete/<int:pk>/', views.CategoriaDelete.as_view(), name='categoria_delete'),
                     ], 'producto')

venta/urls.py
from django.urls import path
from . import views

venta_patterns = ([
                      path('', views.product_list, name='index'),
                      path('ventas/', views.VentaList.as_view(), name='ventas'),
                      path('ventas/detail/<int:pk>/', views.VentaDetail.as_view(), name='detail'),
                      path('ventas/anular/<int:pk>/', views.VentaUpdate.as_view(), name='anular'),
                      path('ventas/facturar/<int:pk>/', views.VentaFactura.as_view(), name='facturar'),
                      path('carrito/', views.carrito, name='carrito'),
                  ], 'venta')

ventas/urls.py
from django.contrib import admin
from django.urls import path, include

from producto.urls import producto_patterns
from venta.urls import venta_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(producto_patterns)),
    path('', include(venta_patterns)),
]

producto/models.py
from django.db import models


# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    descripción = models.CharField(max_length=200)
    precio = models.DecimalField(max_length=10, decimal_places=2, max_digits=10)
    en_stock = models.DecimalField(max_length=4, decimal_places=2, max_digits=4)

    categoria = models.ForeignKey(Categoria, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre + ', precio: ' + self.precio.__str__()

producto/forms.py
from django import forms

from producto.models import Producto, Categoria


class ProductoForm(forms.ModelForm):
    nombre = forms.TextInput(attrs={'class': 'form-control'})
    descripción = forms.TextInput(attrs={'class': 'form-control'})
    precio = forms.DecimalField(initial=00.00, min_value=0,
                                widget=forms.NumberInput(attrs={
                                    'class': 'form-control',
                                }))
    en_stock = forms.DecimalField(initial=00.0, min_value=0,
                                  widget=forms.NumberInput(attrs={
                                      'class': 'form-control',
                                  }))
    categoria = forms.Select(attrs={'class': 'form-control'})

    class Meta:
        model = Producto
        fields = ['nombre', 'descripción', 'precio', 'en_stock', 'categoria']
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre de la materia'
            }),
            'descripción': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Descripción del producto'
            }),
        }
        labels = {}


class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Nombre de la categoría'
            }),
        }

producto/views.py
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView, DeleteView, CreateView

from producto.forms import ProductoForm, CategoriaForm
from producto.models import Producto, Categoria

# Producto Views
from venta.models import Venta


class ProductManage(ListView):
    model = Producto
    template_name_suffix = '_manage'


class ProductCreate(CreateView):
    model = Producto
    form_class = ProductoForm
    success_url = reverse_lazy('producto:manage')


class ProductUpdate(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name_suffix = '_update_form'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProductUpdate, self).get_context_data(**kwargs)
        producto = Producto.objects.get(id=self.kwargs['pk'])
        if not producto:
            raise Http404
        else:
            # Añadimos al contexto el objeto del producto
            context['nombre'] = producto.nombre
        return context

    def get_success_url(self):
        return reverse_lazy('producto:manage')


class ProductoDelete(DeleteView):
    model = Producto
    success_url = reverse_lazy('producto:manage')


# Categoría Views

class CategoriaList(ListView):
    model = Categoria


class CategoriaCreate(CreateView):
    model = Categoria
    form_class = CategoriaForm
    success_url = reverse_lazy('producto:categoria_index')


class CategoriaUpdate(UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name_suffix = '_update_form'

    def get_success_url(self):
        return reverse_lazy('producto:categoria_index')


class CategoriaDelete(DeleteView):
    model = Categoria
    success_url = reverse_lazy('producto:categoria_index')

producto/templates/producto/categoria_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar Categoría{% endblock %}
{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        <h1>{{ object.nombre }}</h1>
                        <form action="" method="post">{% csrf_token %}
                            <p>¿Estás seguro de que quiere borrar esta categoría?</p>
                            <input class="btn btn-danger btn-block" type="submit" value="Sí, borrar el categoría"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

producto/templates/producto/categoria_form.html
{% extends 'core/base.html' %}
{% block title %}
    Crear categoría
{% endblock %}
{% block content %}
    <div class="mt-3 mb-3">
        <h2 class="section-heading mb-2">Creando categoría</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-primary btn-block" type="submit" value="Crear categoría"/>
                <br/>
            </div>
        </form>
    </div>
{% endblock %}

producto/templates/producto/categoria_list.html
{% extends 'core/base.html' %}
{% block title %}
    Gestionar Categorías
{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between mb-4 mt-4">
        <h1 class="">Lista de categorías</h1>
        <div class="mt-2">
            <a href="{% url 'producto:categoria_create' %}" class="btn btn-primary">Crear</a>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Opciones</th>
        </tr>
        </thead>
        <tbody>
        {% for categoria in categoria_list %}
            <tr>
                <td scope="row">{{ categoria.id }}</td>
                <td>{{ categoria.nombre }}</td>
                <td>
                    <a class="btn btn-primary"
                       href="{% url 'producto:categoria_update' categoria.id %}">Editar</a>
                    <a class="btn btn-danger"
                       href="{% url 'producto:categoria_delete' categoria.id %}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

producto/templates/producto/categoria_update_form.html
{% extends 'core/base.html' %}
{% block title %}
    Actualizar categoría
{% endblock %}
{% block content %}
    <div class="mt-3 mb-3">
        <h2 class="section-heading mb-2">Actualizando categoría</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-primary btn-block" type="submit" value="Confirmar"/>
                <br/>
            </div>
        </form>
    </div>
{% endblock %}

producto/templates/producto/producto_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar Producto{% endblock %}
{% block content %}
    <main role="main">
        <div class="container">
            <div class="row mt-3">
                <div class="col-md-9 mx-auto">
                    <div>
                        <h1>{{ object.nombre }}</h1>
                        <p>Descripción: <span>{{ object.descripción }}</span></p>
                        <p>En stock: <span>{{ object.en_stock }}</span></p>
                        <p>Precio: <span>{{ object.precio }}</span></p>
                        <p>Categoría: <span>{{ object.categoria }}</span></p>
                        <form action="" method="post">{% csrf_token %}
                            <p>¿Estás seguro de que quiere borrar este producto?</p>
                            <input class="btn btn-danger btn-block" type="submit" value="Sí, borrar el producto"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

producto/templates/producto/producto_form.html
{% extends 'core/base.html' %}
{% block title %}
    Crear producto
{% endblock %}
{% block content %}
    <div class="mt-3 mb-3">
        <h2 class="section-heading mb-2">Creando producto</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-primary btn-block" type="submit" value="Crear producto"/>
                <br/>
            </div>
        </form>
    </div>
{% endblock %}

producto/templates/producto/producto_manage.html
{% extends 'core/base.html' %}
{% block title %}
    Gestionar Productos
{% endblock %}
{% block content %}
    <div class="d-flex justify-content-between mb-4 mt-4">
        <h1 class="">Lista de productos</h1>
        <div class="mt-2">
            <a href="{% url 'producto:create' %}" class="btn btn-primary">Crear</a>
        </div>
    </div>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripción</th>
            <th scope="col">En stock</th>
            <th scope="col">Categoría</th>
            <th scope="col">Precio</th>
            <th scope="col">Opciones</th>
        </tr>
        </thead>
        <tbody>
        {% for producto in producto_list %}
            <tr>
                <td scope="row">{{ producto.id }}</td>
                <td>{{ producto.nombre }}</td>
                <td>{{ producto.descripción|truncatechars:100 }}</td>
                <td>{{ producto.en_stock }}</td>
                <td>{{ producto.categoria|default:'Sin Categoría' }}</td>
                <td>Bs. {{ producto.precio }}</td>
                <td>
                    <a class="btn btn-primary"
                       href="{% url 'producto:update' producto.id %}">Editar</a>
                    <a class="btn btn-danger"
                       href="{% url 'producto:delete' producto.id %}">Eliminar</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

producto/templates/producto/producto_update_form.html
{% extends 'core/base.html' %}
{% block title %}
    Actualizar producto
{% endblock %}
{% block content %}
    <div class="mt-3 mb-3">
        <h2 class="section-heading mb-2">Actualizando producto</h2>
        <p class="h5">Usted está actualizando: {{ nombre }}</p>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="text-center">
                <input class="btn btn-primary btn-block" type="submit" value="Actualizar producto"/>
                <br/>
            </div>
        </form>
    </div>
{% endblock %}